
package smallsimpleapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 * Small Interactive Swing App to demo jpackage
 * @author jbf
 */
public class SmallSimpleApp extends javax.swing.JPanel {

    /**
     * Creates new form SmallSimpleApp
     */
    public SmallSimpleApp() {
        initComponents();
    }

    long finishTime;
    int durationMs;
    Timer t;
            
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        durationGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sec05 = new javax.swing.JRadioButton();
        sec25 = new javax.swing.JRadioButton();
        secCustom = new javax.swing.JRadioButton();
        secCustomField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        durationProgress = new javax.swing.JProgressBar();
        currentTimeLabel = new javax.swing.JLabel();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+4f));
        jLabel1.setText("Rabbit Timer");

        jLabel2.setText("Duration");

        durationGroup.add(sec05);
        sec05.setSelected(true);
        sec05.setText("5 sec");

        durationGroup.add(sec25);
        sec25.setText("25 sec");

        durationGroup.add(secCustom);
        secCustom.setText("custom:");

        secCustomField.setText("60");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, secCustom, org.jdesktop.beansbinding.ELProperty.create("${selected}"), secCustomField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        startButton.setText("Start Timer");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        currentTimeLabel.setFont(currentTimeLabel.getFont().deriveFont(currentTimeLabel.getFont().getSize()+10f));
        currentTimeLabel.setText("--------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sec25)
                                .addComponent(sec05)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(secCustom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(secCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(startButton)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(currentTimeLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(durationProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sec05)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sec25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secCustom)
                    .addComponent(secCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startButton)
                .addGap(26, 26, 26)
                .addComponent(durationProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTimeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if ( sec05.isSelected() ) {
            durationMs= 5000;
        } else if ( sec25.isSelected() ) {
            durationMs= 25000;
        } else {
            durationMs= Integer.parseInt( secCustomField.getText() ) * 1000;
        }
        finishTime= System.currentTimeMillis() + durationMs;
        currentTimeLabel.setText( String.format( "%.1f seconds", ( finishTime - System.currentTimeMillis() ) / 1000. ) );
        durationProgress.setMaximum( durationMs );
        startButton.setEnabled(false);
        startTimer();
    }//GEN-LAST:event_startButtonActionPerformed

    public void startTimer() {
        t= new Timer( 100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int elapsedMillis= (int)( System.currentTimeMillis() - ( finishTime - durationMs ) );
                if ( elapsedMillis>=durationMs ) {
                    currentTimeLabel.setText( String.format( "%.1f seconds", ( durationMs / 1000. ) ) );
                    durationProgress.setValue( durationMs );
                    startButton.setEnabled(true);
                    t.stop();
                } else {
                    currentTimeLabel.setText( String.format( "%.1f seconds", ( elapsedMillis / 1000. ) ) );
                    durationProgress.setValue( elapsedMillis );
                }
            }
        } );
        t.setRepeats(true);
        t.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentTimeLabel;
    private javax.swing.ButtonGroup durationGroup;
    private javax.swing.JProgressBar durationProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton sec05;
    private javax.swing.JRadioButton sec25;
    private javax.swing.JRadioButton secCustom;
    private javax.swing.JTextField secCustomField;
    private javax.swing.JButton startButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
